### ISSUE TITLE
Supervisor in Go instead of Python

### ISSUE THREAD

**Issue by vojtechmares** [dockette/web#4]
Hi!

I suggest replacing the standard supervisord from packages (I am talking about Alpine) with single binary written in Go from https://hub.docker.com/r/ochinchina/supervisord

The benefit of this change is that we will get rid of some overhead from Python environment which supervisor brings. So the image is overall smaller.

We need to add/change this in Dockerfile:
```
# ...
COPY --from=ochinchina/supervisord:latest /usr/local/bin/supervisord /usr/local/bin/supervisord
#...
CMD [ "/usr/local/bin/supervisord", "-c", "supervisor.conf", "-d" ]
```

**Comment by f3l1x** [comment]
Thanks, I deprecated Alpine version. But I used this approach in alpined-based images. So good advice, thx @vojtechmares.
