### ISSUE TITLE
buster distro reached EOL

### ISSUE THREAD

**Issue by krkabol** [dockette/web#8]
Due the EOL (https://endoflife.date/debian) the https://packages.sury.org/php/dists/buster/ does not provide packages anymore and the images are not possible to build.

Please see attached patch upgrading to booksworm.
PS - sorry for the patch instead of a pull request, but I followed the instruction  "how to contribute" README.md:83 and reached a dead end :-)

thank you for your work
best
Petr

[standardize_apt_apt-get_usage_exclude_mongo_as_unavailable_from_unknown_reason_remove_depr.zip](https://github.com/user-attachments/files/16128166/standardize_apt_apt-get_usage_exclude_mongo_as_unavailable_from_unknown_reason_remove_depr.zip)

**Comment by f3l1x** [comment]
Patch applied, thank you.
